### PR TITLE
Add information

### PR DESCRIPTION
**Pull request by zhangyuchen584**
1. move the 'welcome', 'about' section from home page to 'about' page.
2. in 'organization' page, add 'Previous Officers' button to show the historical officers, so add an additional 'officers.md'
3. add 'information' page, which show public and private information.

Any problem please let me know ASAP, thank you.

### CODE REVIEW

**Comment by desilinguist** [comment]
Does this PR replace the previous PR?

**Comment by zhangyuchen584** [comment]
yes, please ignore the previous one

**Comment by desilinguist** [comment]
There was really no need to create an entirely new PR, you could have just edited the previous one. In any case, here are my responses to your comments in the previous PR:

> The officers considered the private information is necessary, so could you make this repository private?

Since the sigdat-org GitHub account is a free one, it cannot serve a public Github Pages website from a private repository. In any case, making the repository private is pointless because _anyone_ can simply view the source of the website from the browser and see the password. Therefore, the information is not private but fully public. If private information is indeed necessary, please use a shared google doc with appropriate permissions. A fully static GitHub Pages site is not appropriate for private information.

> Your advice is greatly appreciated. Maybe later will add 'old news' button when SIGDAT have more news in the future, and the officers prefer current format and think no need to consistent with the other 2 websites.

I am at a loss to understand why the SIGDAT officers would make such a decision especially when being provided specific recommendations by the ACL Information Director. However, if this is the way they want to proceed, it's their choice.

For any further discussions, it is probably better to start an email thread with myself and the SIGDAT officers.

**Comment by zhangyuchen584** [comment]
please take a look about the updated version, I add passwords to the private files instead of add password to the information webpage.

**Comment by zhangyuchen584** [comment]
if any problem with my updated version, please let me know.

**Comment by desilinguist** [comment]
Thank you for fixing the private information issue! However, there are still several issues with this PR:

1. Unnecessary mixing of markdown and HTML content.
2. Non-conformance with the design of other SIG websites. 
3. Incorrectly removed HTML tags from theme layout files.
4. Usage of hard-coded font sizes when one can use relative font sizes already defined in the theme.
5. Missing link to EMNLP 2019 in the Past Events page. 

I am going to take this PR and create a new PR with the same content but with the stylistic issues fixed.

**Pull request closed without merging**
