### PR TITLE
Add CFB for EMNLP 2023: CFB-2023.md; Add CFB info on home.md

### PR DESCRIPTION
**Pull request by ptlord**
Hi Nitin,

I add a CFB for EMNLP 2023 (CFB-2023.md) and update the info on the home.md page. Please check.

Best,

CY

### CODE REVIEW

**Comment by desilinguist** [comment]
Hi @ptlord. I noticed a bunch of issues here:

- We have enough news items now to warrant a news archive for older items. 
- It would be better to have a separate “Calls” section in the top menubar to host all future calls instead of just adding them one off.
- There are several typos and incorrect links in the CFB page that was added.
- This branch seems out of date with the current master branch. You need to make sure that you run `git pull` in your local working copy before you create new branches and pull requests.

I will work on fixing all of these now.

**Comment by ptlord** [comment]
Got it, I forget that you had made chances.
Sorry that I made you do extra work.
Yes, please create a Calls tab. Do you want me to do it?

Best,

CY
________________________________

**Comment by desilinguist** [comment]
No worries. I am almost done! :)

**Comment by ptlord** [comment]
Thanks!

Best,

CY
________________________________

**Review by desilinguist — APPROVED** [review]

**Comment by ptlord** [comment]
They look very nice to me.
Thank you Nitin!

Best,

CY
________________________________

**Comment by desilinguist** [comment]
Great! You’re welcome!
________________________________

**Pull request merged**
